addition of multi-set
glittershark/core-async-storage pull request #3
Opened 2017-02-26 18:05 UTC by derHowie

2017-02-27 01:04 UTC, glittershark requested changes
Like the API quite a bit overall. Would you mind putting this all in one commit, though, in addition to removing the swap file ignore?

Thanks for the PR!

2017-02-27 01:04 UTC, glittershark commented on .gitignore
> +*.swp
I generally don't like to pollute repo-specific .gitignores with editor or tool-specific items. This can go in a global gitignore

2017-02-27 01:27 UTC, derHowie commented
No problem, I squashed the commits and restored the .gitignore file.

2017-03-01 16:40 UTC, derHowie commented
@glittershark, this PR now includes multi-remove as well

2017-03-01 19:59 UTC, merged

2017-03-01 20:00 UTC, glittershark commented
Thanks! Will push out a version soon.